export const COD_CAT_APO_EN_CRCA: number = 64 // CODIGO TIPO DE APORTE EN CRCA
export const COD_CAT_FUE_ING_CRCA: number = 86 // CODIGO TIPO DE FUENTES DE INGRESOS DE LA OP
export const COD_DAT_PERSONAL: number = 21 // TEMPORAL - CODIGO DATO PERSONAL
export const COD_UNI_APORTE_EN_CHEQUE: number = 66 // CHEQUE - CRCA NUMERARIO
export const COD_UNI_APORTE_EN_TRANSFERENCIA: number = 67 // TRANSFERENCIA - CRCA NUMERARIO
export const COD_UNI_APORTE_EN_OTROS: number = 70 // OTROS - CRCA NUMERARIO

export const COD_CAT_BNC_CRCA: number = 91 // CODIGO UNICO - FILTRO CATALOGO DE BANCOS CRCA

